# Generated by Django 4.0.3 on 2022-04-16 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyTitle', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=50)),
                ('SubCategory', models.CharField(max_length=50)),
                ('Purpose', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField()),
                ('Longitude', models.FloatField()),
                ('Latitude', models.FloatField()),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('LandArea', models.IntegerField()),
                ('Unit', models.CharField(max_length=255)),
                ('BedRooms', models.IntegerField()),
                ('BathRooms', models.IntegerField()),
                ('Structureype', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
